language: python
python:
  - 3.3
  - 3.4

install: pip install -r requirements.txt
script: flake8 --max-complexity 10 .

notifications:
  email:
    recipients:
      - LDR-Importer@noreply.github.com
    on_success: change
    on_failure: change
